# Generated by Django 3.0.7 on 2020-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_dinner_platter_pasta_regular_pizza_salad_sicilian_pizza_sub_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order_no', models.IntegerField()),
                ('items', models.CharField(max_length=5000)),
            ],
        ),
    ]
