# Generated by Django 3.1.3 on 2021-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20210201_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_cost',
            field=models.FloatField(),
        ),
    ]
