# Generated by Django 3.0.7 on 2020-07-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_user_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order_no', models.IntegerField()),
                ('items', models.CharField(max_length=5000)),
                ('time_ordered', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='user_orders',
        ),
    ]
