# Generated by Django 3.1.3 on 2021-02-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20210201_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_size',
            field=models.CharField(choices=[('Small', 'S'), ('Large', 'L'), ('NA', 'N')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Could not be Completed', 'Could not be Completed')], default=None, max_length=64, null=True),
        ),
    ]
