# Generated by Django 3.0.7 on 2020-07-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='items',
            field=models.TextField(),
        ),
    ]
