# Generated by Django 3.0.7 on 2020-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20200719_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
