# Generated by Django 3.1.3 on 2021-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20210202_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Could not be Completed', 'Could not be Completed')], default='Processing', max_length=64, null=True),
        ),
    ]
