# Generated by Django 3.0.7 on 2020-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_user_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=4),
            preserve_default=False,
        ),
    ]
